#!/usr/bin/env node
/**
 * Writes docs/SOUL_JAM_MASTER_SKELETON.md from the game's reference rig (lib/mocap/mhr-rigs/player.json.gz)
 * and the persistent Tripo mapping — the document is generated, so it can't drift from the data.
 *   node tools/character_pipeline/skeleton-doc.mjs
 */
import fs from 'fs';
import path from 'path';
import zlib from 'zlib';
import { ROOT, RIGS_DIR } from './config.mjs';

const r = JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(RIGS_DIR, 'player.json.gz'))));
const M = r.mhr;
const map = JSON.parse(fs.readFileSync(path.join(ROOT, 'tools', 'character_pipeline', 'tripo_to_souljam_bones.json'), 'utf8'));
const kids = M.names.map(() => []); M.parents.forEach((p, i) => { if (p >= 0) kids[p].push(i); });
const root = M.parents.indexOf(-1);
const f = (v) => v.map((x) => x.toFixed(3)).join(', ');
const lines = [];
(function walk(i, d) { lines.push(`${'  '.repeat(d)}${M.names[i]}  (${f(M.bindPos[i])})`); kids[i].forEach((c) => walk(c, d + 1)); })(root, 0);
const twist = M.names.filter((n) => /twist/.test(n)), fingers = M.names.filter((n) => /(thumb|index|middle|ring|pinky)/.test(n));
const Y = M.bindPos.map((p) => p[1]);
const md = `# SOUL_JAM_MASTER_SKELETON

Generated by \`tools/character_pipeline/skeleton-doc.mjs\` from \`lib/mocap/mhr-rigs/player.json.gz\` (${new Date().toISOString().slice(0, 10)}). Every Soul Jam player — the built-in ones and every Character Factory character — is bound to this skeleton.

| Fact | Value |
|---|---|
| Joints | **${M.names.length}** (MHR body model) |
| Root | \`${M.names[root]}\` → \`root\` (pelvis) → spine \`c_spine0…3\` → \`c_neck\` → \`c_head\` |
| Units / scale | metres; reference height ${r.heightM} m (bind pose, feet on y = 0; joint y from ${Math.min(...Y).toFixed(3)} to ${Math.max(...Y).toFixed(3)}) |
| Axes | +Y up, the character faces **+Z**, its left is +X (glTF / three.js) |
| Rest pose | the bind pose below (\`bindPos\`, \`bindRot\` quaternions); per-character proportions are refitted onto the same joint set (\`restJoints\`, \`boneLen\`, \`legLen\`, \`soleOffset\` in each rig) |
| Twist joints | ${twist.length}: ${twist.join(', ')} |
| Finger joints | ${fingers.length} (thumb 0–3, index / middle / ring 1–3, pinky 0–3, tip nulls) |
| IK bones | none — IK is solved at runtime (\`engine3d/contact-ik.mjs\`, leg solver in \`anim3d.mjs\`) |
| Facial bones | none (see the facial standard note in docs/character-factory-plan.md §12) |
| Root motion | clips carry it separately (\`rootMotion\`: dx, dz, dyaw per frame, root space); the skeleton itself is posed in world space by the runtime |
| Skinning | 4 influences per vertex (the renderer's limit), weights normalised |
| Animation | keypoint clips (70 MHR70 keypoints) → \`engine3d/mhr-skin.mjs\` solves these ${M.names.length} joints for any rig; no per-character retarget |

## Tripo / Mixamo → master mapping

Persistent file: \`tools/character_pipeline/tripo_to_souljam_bones.json\` (written once, read by every import).

| Source bone | Fitted onto |
|---|---|
${Object.entries(map.target).map(([k, v]) => `| ${k} | ${v} |`).join('\n')}

Weights of each source bone are spread over these master joints (twist joints included):

| Source bone | Master joints |
|---|---|
${Object.entries(map.weights).map(([k, v]) => `| ${k} | ${v.join(', ')} |`).join('\n')}

UE4 / UE5 Mannequin names map onto the Mixamo names first (\`ueMannequin\` in the file). Fingers are re-rigged one finger per vertex along that finger's own joints.

## Hierarchy (bind position, metres)

\`\`\`
${lines.join('\n')}
\`\`\`
`;
fs.writeFileSync(path.join(ROOT, 'docs', 'SOUL_JAM_MASTER_SKELETON.md'), md);
console.log('wrote docs/SOUL_JAM_MASTER_SKELETON.md');
